### ISSUE TITLE
Tasks for Release of Multi-Cal Update

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-talk-gcalendar-extension#41]
We're soon going to release a major update to the extension which adds support for multiple calendars. Here are a few associated tasks which need to be completed:

```[tasklist]
### Tasks
- [x] Update Extension Manifest
- [x] Update Google Dashboard Extension Details
- [x] Update https://brave.com/talk/ as needed
- [x] Update [support.brave.com](https://support.brave.com/hc/en-us/categories/16067800578957-Brave-Talk) as needed
```
